dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
install:
  - python setup.py install
before_script:
  - pip install python-coveralls
script:
  - python setup.py test
after_success:
  - coveralls
